// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvFXZeiMtUswMf0cK58X9XCHYxiut11WI',
    appId: '1:253818539733:web:45c16a507cfde7b87c5c5c',
    messagingSenderId: '253818539733',
    projectId: 'todo-d8480',
    authDomain: 'todo-d8480.firebaseapp.com',
    storageBucket: 'todo-d8480.firebasestorage.app',
    measurementId: 'G-Z2Z22Z0KR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0IYd7icvwQAP_PUspVJuLJg9m-dAAJUY',
    appId: '1:253818539733:android:c4c81a7b635a60567c5c5c',
    messagingSenderId: '253818539733',
    projectId: 'todo-d8480',
    storageBucket: 'todo-d8480.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZy0na_rnKwlGDprIwLYTn4xulsAKXeCM',
    appId: '1:253818539733:ios:317fecc09bcf08657c5c5c',
    messagingSenderId: '253818539733',
    projectId: 'todo-d8480',
    storageBucket: 'todo-d8480.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZy0na_rnKwlGDprIwLYTn4xulsAKXeCM',
    appId: '1:253818539733:ios:317fecc09bcf08657c5c5c',
    messagingSenderId: '253818539733',
    projectId: 'todo-d8480',
    storageBucket: 'todo-d8480.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvFXZeiMtUswMf0cK58X9XCHYxiut11WI',
    appId: '1:253818539733:web:61fac3a0e3c7898e7c5c5c',
    messagingSenderId: '253818539733',
    projectId: 'todo-d8480',
    authDomain: 'todo-d8480.firebaseapp.com',
    storageBucket: 'todo-d8480.firebasestorage.app',
    measurementId: 'G-JQGXFLQ0HQ',
  );

}